Создание каркаса Spring Boot приложения Filmorate
KoltsovaIA/java-filmorate pull request #4
Opened 2023-04-06 18:41 UTC by KoltsovaIA

2023-04-08 12:29 UTC, Frilock requested changes
Добрый день, оставил ряд комментариев к Вашей работе. Жду новую версию

2023-04-08 12:29 UTC, Frilock commented on pom.xml
> +			<version>4.12</version>
Версии библиотек, которые вы подключаете в pom файле, принято указывать в properties, по аналогии с версией Java, а в поле version самой библиотеки указывать так ${example-lib.version}. Это нужно для того, чтобы версии библиотек находились в одном месте и их изменении проходило безболезненно.

2023-04-08 12:29 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (film.getName() == null || film.getName().isBlank()) {
Смотрите, можно воспользоваться библиотекой от apache common 3 - StringUtils.isBlank(...)
На самом деле в ней много полезных функций

2023-04-08 12:29 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (film.getDescription().length() > 200) {
Все эти проверки нужно вынести в отдельный приватный метод.

2023-04-08 12:29 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28)) ||
Не правильные проверки, они идут слева на право, и если дата null вы получите ошибку

2023-04-08 12:29 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            create(film);
Лишняя вложенность, вы можете просто сделать return create(...)
а другой блок уже писать не в блоке else

2023-04-08 12:29 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        if (user.getEmail() == null || user.getEmail().isBlank()) {
Комментарии аналогичны предыдущему контроллеру, по этому писать их тут не буду

2023-04-08 12:29 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/FilmAlreadyExistException.java
> +        log.error(message);
Лучше сначала в лог писать все же. Но вообще обычно в кастомных классах исключений вызывается только супер, логгировать обычно тут не принято ошибку

2023-04-08 12:29 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +public class User {
Вообще можете поиграться с зависимостями:
1. Для улучшения валидации, можно воспользоваться зависимостью:
 В данном случае на поля класса модели можно повесить дополнительные аннотации, например,
@NotNull к полю для проверки на null, @NotBlank — для проверки на пустую строку, @Email — для проверки на соответствие формату электронного адреса.

2023-04-08 12:29 UTC, Frilock commented on pom.xml
> +			<artifactId>spring-boot-starter-validation</artifactId>
Вообще не вижу использования данной зависимости (мб проглядел)

2023-04-08 12:29 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +    FilmController filmController = new FilmController();
Модификатор необходимо добавить

2023-04-08 12:29 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/controllers/UserControllerTest.java
> +    UserController userController = new UserController();
Модификатор

2023-04-08 12:59 UTC, KoltsovaIA commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/FilmAlreadyExistException.java
> +        log.error(message);
В конструкторе сначала вызывается super. Поэтому просто уберем логгирование?

2023-04-09 14:35 UTC, KoltsovaIA commented on pom.xml
> +			<artifactId>spring-boot-starter-validation</artifactId>
Пыталась валидировать не только запросы со стороны клиента с помощью аннотаций, но и передачу параметров методам, пока ничего не вышло. Подскажите пожалуйста, что надо почитать на эту тему

2023-04-09 14:37 UTC, KoltsovaIA commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +public class User {
посмотрите в ответе на

> <artifactId>spring-boot-starter-validation</artifactId>

2023-04-09 19:34 UTC, Frilock commented on pom.xml
> +			<artifactId>spring-boot-starter-validation</artifactId>
Можно посмотреть статью одного из ваших наставников https://struchkov.dev/blog/ru/spring-boot-validation/
Там также еще полезные статьи есть, например, по исключения.

2023-04-09 19:36 UTC, Frilock approved these changes
Принято, в некоторых местах не удалили аннотации, но не критично.
Статью по вашей просьбе в комментарии приложил

2023-04-09 19:36 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/UserBirthdayException.java
> +@Slf4j
Лишние аннотации в классах исключений

2023-04-16 06:13 UTC, merged